<link rel="stylesheet" href="../../css/footer.css">
<section class="footer">
    <div class="box-container">
        <!--
        <div class="box">
            <h3>Вернуться</h3>
            <a href="#home">Главная</a>
            <a href="#about">О нас</a>
            <a href="#contact">Связаться с нами</a>
        </div>
        Вставка видео -->
        <div class="box">
            <h3>Адрес</h3>
            <a>Россия, г. Казань,</a>
            <a>улица Каплма Маркса 74</a>

        </div>
        <div class="box">
            <h3>Перейти</h3>
            <a href="#">Личный кабинет</a>
            <a href="#">Корзина</a>
            <a href="index.phtml">Главная</a>
        </div>


        <div class="box">
            <h3>Контактные данные</h3>
            <a href="#">89656236637</a>
            <a href="#">sabirzyanova_inzilya31@mail.ru</a>
        </div>

        <div class="url">
            <a href="https://vk.com/parfum"><img src="../../images/vk.png" /></a>
            <a href="https://t.me/s/instagram"><img src="../../images/instagram.png"/></a>
            <a href="https://web.telegram.org"><img src="../../images/telegram.png"/></a>
        </div>

    </div>

    <div class="credit">Created by Inzilya</div>

</section>
</body>
</html>
