<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>О нас</title>
    <link rel="stylesheet" href="../css/about.css">
</head>
<body>
<div class="about-section">

    <h1>Хорошие духи создают настроение.. </h1>
    <p>Лучшие — говорят о тебе без слов.</p>
</div>


<section class="about">

    <div class="row">
        <div class="image-container">
            <img src="../images/adelivery.png"></img>
        </div>
        <!-- текстовая часть -->
        <div class="content">
            <h3>Доставка по всей России</h3>
            <p> Мы объединяемся с зарубежными производителями и партнерами для того,
                чтобы производить только качественную продукцию, отвечающую всем
                современным требованиям.  </p>
            <p>Наша команда – это команда увлеченных профессионалов,
                c главным принципом клиенто- орентированности в работе.
                Мы работаем для того, чтобы каждая женщина могла прикоснуться
                к миру профессиональной индустрии красоты, и сделать этот мир
                чуточку прекраснее.
            </p>
        </div>
    </div>

    <div class="row">
        <div class="image-container">
            <img src="../images/agift.png"></img>
        </div>

        <!-- текстовая часть -->
        <div class="content">
            <h3>Вы не останетесь без подарка</h3>
            <p> Мы объединяемся с зарубежными производителями и партнерами для того,
                чтобы производить только качественную продукцию, отвечающую всем
                современным требованиям.  </p>
            <p>Наша команда – это команда увлеченных профессионалов,
                c главным принципом клиенто- орентированности в работе.
                Мы работаем для того, чтобы каждая женщина могла прикоснуться
                к миру профессиональной индустрии красоты, и сделать этот мир
                чуточку прекраснее.
            </p>
        </div>
    </div>

    <div class="row">
        <div class="image-container">
            <img src="../images/alove.png"></img>
        </div>

        <!-- текстовая часть -->
        <div class="content">
            <h3>Благотворительность, любовь, мир</h3>
            <p> Мы объединяемся с зарубежными производителями и партнерами для того,
                чтобы производить только качественную продукцию, отвечающую всем
                современным требованиям.  </p>
            <p>Наша команда – это команда увлеченных профессионалов,
                c главным принципом клиенто- орентированности в работе.
                Мы работаем для того, чтобы каждая женщина могла прикоснуться
                к миру профессиональной индустрии красоты, и сделать этот мир
                чуточку прекраснее.
            </p>
        </div>
    </div>

</section>

<section class="line">
    <p>Наша команда</p>
    <hr>
</section>

<h2 style="text-align:center"></h2>
<div class="row">
    <div class="column">
        <div class="card">
            <img src="../images/girl1.png" alt="Jane" style="width:100%">
            <div class="container">
                <h2>Сафия Тюдор</h2>
                <p class="title">директор </p>
                <p>Главный спонсор проекта, готовый к новым бизнес-партернствам</p>
                <p class="p">saf@gmail.com</p>
            </div>
        </div>
    </div>

    <div class="column">
        <div class="card">
            <img src="../images/girl2.png" alt="Mike" style="width:100%">
            <div class="container">
                <h2>Киану Ривз</h2>
                <p class="title">Гланый парфюмер</p>
                <p>Именно с его подачи (с подачи Киану Ривза) выбираются линейки парфюмерии</p>
                <p class="p">kianu@gmail.com</p>
            </div>
        </div>
    </div>

    <div class="column">
        <div class="card">
            <img src="../images/girl3.png" alt="John" style="width:100%">
            <div class="container">
                <h2>Анжелла Версачи</h2>
                <p class="title">Байер</p>
                <p>Эта прекрасная женщина занимается закупками импортных ароматов и является нашим байером.</p>
                <p class="p">angel@mail.ru</p>
            </div>
        </div>
    </div>
</div>

<section class="line">
    <hr>
</section>

<?php  include("template/footer.phtml"); ?>