<?php include ("template/header.phtml")?>

<section class="log" id="log">
    <div class="row">
        <form action="auto.phtml" method="post">
            <input type="text" name="login" value="" placeholder="Логин" class="box">
            <input type="password" name="pass" value="" placeholder="Пароль" class="box">
            <input type="submit" value="Отправить" class="btn">
        </form>

    </div>
    <a  href="registration.phtml">Зарегистрироваться</a>
</section>



